baseURL = "https://become-hindu.github.io/"
languageCode = "en-us"
title = "Become Hindu! घर वापसी!"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/become-hindu/become-hindu.github.io/edit/hugo-source/content/"
  contactLink = "https://github.com/become-hindu/become-hindu.github.io/issues/new"
  build_img = "https://github.com/become-hindu/become-hindu.github.io/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/become-hindu/become-hindu.github.io/actions/workflows/build.yml"
  env = "production"
#  disqusShortcode = "hindu-vichaarah"
  background_color_class = "bg-light-red"
  body_classes = "bg-washed-yellow"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true